execute pathogen#infect()

syntax on
set smartindent

set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set laststatus=2

set number
set cursorline
set showmatch
set incsearch
set hlsearch

set background=dark
colorscheme jellybeans
let g:jellybeans_use_term_italics = 1
if !has('gui_running')
  set t_Co=256
endif

"let g:lightline = {
"      \ 'colorscheme': 'jellybeans',
"      \ }
let g:lightline = {
  \   'colorscheme': 'jellybeans',
  \   'active': {
  \     'left':[ [ 'mode', 'paste' ],
  \              [ 'gitbranch', 'readonly', 'filename', 'modified' ]
  \     ]
  \   },
	\   'component': {
	\     'lineinfo': ' %3l:%-2v',
	\   },
  \   'component_function': {
  \     'gitbranch': 'fugitive#head',
  \   }
  \ }
let g:lightline.separator = {
	\   'left': '', 'right': ''
  \}
let g:lightline.subseparator = {
	\   'left': '', 'right': '' 
  \}

filetype plugin indent on

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

map <C-Left> <Esc>:bprev<CR>
map <C-Right> <Esc>:bnext<CR>

map <C-b> :NERDTreeToggle<CR>
map <C-h> <A-Left>
map <C-l> <A-Right>

nnoremap <S-Up> :m-2<CR>
nnoremap <S-Down> :m+<CR>
inoremap <S-Up> <Esc>:m-2<CR>
inoremap <S-Down> <Esc>:m+<CR>

set noruler
set noshowmode
set hidden

