# Author: Rob Lyon <rob@ctxswitch.com>

# Syntax.
"comment" = { fg = "grey" }
"constant" = { fg = "magenta" }
"constant.character.escape" = { fg = "red" }
"constant.numeric" = { fg = "red" }
"constructor" = { fg = "red_highlight" }
"function" = { fg = "purple" }
"function.macro" = { fg = "purple" }
"function.special" = { fg = "purple" }
"keyword" = { fg = "yellow" }
"keyword.control" = { fg = "yellow_highlight" }
"keyword.directive" = { fg = "red_highlight" }
"namespace" = { fg = "purple" }
"operator" = { fg = "grey_highlight" }
"punctuation" = { fg = "grey_highlight" }
"punctuation.special" = { fg = "red" }
"string" = { fg = "green" }
"string.regexp" = { fg = "green_highlight" }
"string.special.path" = { fg = "foreground" }
"tag" = { fg = "grey" }
"type" = { fg = "purple" }
"type.builtin" = { fg = "red" }
"type.enum.variant" = { fg = "red_highlight" }
"variable" = { fg = "yellow" }

# Diff.
"diff.delta" = { fg = "purple_highlight" }
"diff.minus" = { fg = "red" }
"diff.plus" = { fg = "green" }

# Interface / markup.
"markup.bold" = { fg = "blue" }
"markup.heading" = { fg = "green_highlight" }
"markup.italic" = { fg = "yellow" }
"markup.link.text" = "magenta"
"markup.link.url" = "deepblue_highlight"
"markup.list" = "deepblue_highlight"
"markup.quote" = { fg = "yellow" }
"markup.raw" = { fg = "grey_highlight" }
"markup.raw.inline" = { fg = "red" }

# UI.
"ui.background" = { fg = "foreground", bg = "background" }
"ui.cursor" =  { fg = "background", bg = "cursor_secondary", modifiers = ["dim"] }
"ui.cursor.match" = { fg = "yellow", modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "background", bg = "cursor_primary", modifiers = ["dim"] }
"ui.cursorline" = { bg = "background_ui" }
"ui.gutter" = { bg = "background"}
"ui.help" = { fg = "grey_highlight", bg = "background_ui" }
"ui.linenr" = { fg = "grey" }
"ui.linenr.selected" = { fg = "blue_highlight" }
"ui.menu" = { fg = "grey_highlight", bg = "background_ui" }
"ui.menu.selected" = { fg = "blue_highlight", bg = "background_ui" }
"ui.popup" = { fg = "grey_highlight", bg = "background_ui" }
"ui.selection" = { bg = "highlight_secondary" }
"ui.selection.primary" = { bg = "highlight_primary" }
"ui.statusline" = { fg = "purple", bg = "statusline" }
"ui.statusline.inactive" = { fg = "purple", bg = "statusline" }
"ui.text" = { fg = "foreground" }
"ui.text.focus" = { fg = "blue_highlight" }
"ui.virtual.ruler" = { bg = "background" }
"ui.virtual.whitespace" = { fg = "grey" }
"ui.window" = { fg = "background_ui" }

# Diagnostics (gutter).
"diagnostic.error" = { fg = "error" }
"diagnostic.hint" = { fg = "ok" }
"diagnostic.warning" = { fg = "warning" }

# Diagnostics (window).
"error" = { fg = "error" }
"warning" = { fg = "warning" }

[palette]

foreground = "#d5d5d5"
background = "#151515"
background_ui = "#3b3b3b"

statusline = "#555555"

error = "#e98466"
warning = "#f2c766"
ok = "#b3c784"

cursor_primary = "#636363"
cursor_secondary = "#adadad"
highlight_primary = "#31647d"
highlight_secondary = "#343947"

red = "#cf6a4c"
red_highlight = "#f79274"
green = "#99ad6a"
yellow = "#d8ad4c"
yellow_highlight = "#f79274"
deepblue = "#597bc5"
deepblue_highlight = "#81a3ed"
purple = "#a037b0"
blue = "#71b9f8"
blue_highlight = "#99e1ff"
grey = "#636363"
grey_highlight = "#adadad"
magenta = "#c85fd8"

