#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export EDITOR=vim

# Add cargo to the path if we have rust installed
if [ -d $HOME/.cargo/bin ] ; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi

