if [[ -d /Applications ]]; then
  export PATH=$PATH:/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export EDITOR=vim
export GIT_EDITOR=vim

mkdir -p $HOME/bin
export PATH="$HOME/bin:$PATH"

# Add goroot and gopath
# export GOROOT=/usr/local/go
export PATH=/usr/local/kubebuilder/bin:$PATH

# Add cargo to the path if we have rust installed
# if [ -d $HOME/.cargo/bin ] ; then export PATH="$HOME/.cargo/bin:$PATH"; fi

# Add completion for kubectl
KUBECTL_BIN=$(which kubectl)
if [ -f ${KUBECTL_BIN} ]; then . <(${KUBECTL_BIN} completion zsh); fi

# Add the path for rbenv if it exists
if [ -d ~/.rbenv/bin ] ; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"  
fi

export PATH=$PATH:/usr/local/kubebuilder/bin

if [ -f ${HOME}/.zshrc.local ]; then . ${HOME}/.zshrc.local; fi

if [ -d /opt/homebrew ]; then eval "$(/opt/homebrew/bin/brew shellenv)"; fi

if [ -d $(go env GOPATH)/bin ]; then
  export PATH=$(go env GOPATH)/bin:$PATH
fi

export GPG_TTY=$(tty)
