# Create a new tmux root session if one doesn't exist.
tmux has-session -t root 2>/dev/null || tmux new-session -s root -d

mkdir -p $HOME/bin

KUBECTL_BIN=$(which kubectl)

export EDITOR=nvim
export GIT_EDITOR=nvim

export PATH="$HOME/bin:$PATH"
export PATH=/usr/local/go/bin:/usr/local/kubebuilder/bin:$PATH
export PATH=/usr/local/opt/llvm/bin:$PATH
export PATH=$PATH:/usr/local/kubebuilder/bin

HOMEBREW_PATH=$([[ "$(uname -s)" == "Darwin" ]] && echo "/opt/homebrew" || echo "/home/linuxbrew/.linuxbrew")
[ -d $HOMEBREW_PATH ] && eval "$($HOMEBREW_PATH/bin/brew shellenv)"

# Add Visual Studio Code (code) to the path if we have it installed.  This will go
# away once I've fully migrated to nvim.
[[ -d /Applications/Visual\ Studio\ Code.app ]] && \
	export PATH=$PATH:/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin
# Add cargo to the path if we have rust installed.
[ -d $HOME/.cargo/bin ] && export PATH="$HOME/.cargo/bin:$PATH"
# Add go to the path if we have it installed.
[ -d $(go env GOPATH)/bin ] && export PATH=$(go env GOPATH)/bin:$PATH

[ -f ${HOME}/.zshrc.local ] && source ${HOME}/.zshrc.local

# Source Prezto.
[[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]] && source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
# Add completion for kubectl
[ -f ${KUBECTL_BIN} ] && . <(${KUBECTL_BIN} completion zsh)

export GPG_TTY=$(tty)
export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --exclude .git --exclude vendor'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Helper functions
function cds() {
	S=$(FZF_DEFAULT_COMMAND="fd . --type d --max-depth 3 --exclude .git --exclude vendor --exclude node_modules ~/src" fzf)
	cd ${S}
}

function cdt() {
	S=$(FZF_DEFAULT_COMMAND="fd . --type d --max-depth 3 --exclude .git --exclude vendor --exclude node_modules ~/src" fzf)
	cd ${S}
	N=$(basename $S)
	tmux neww -n $N
}

function nvt() {
	S=$(FZF_DEFAULT_COMMAND="fd . --type d --max-depth 3 --exclude .git --exclude vendor --exclude node_modules ~/src" fzf)
	cd ${S}
	N=$(basename $S)
	tmux neww -n $N 'exec nvim .'
	tmux split-window -v -p 20
}

alias vim=nvim
alias code=nvim

